language: node_js
node_js: 6
branches:
  except:
    - /^\d+\.\d+\.\d+/
script:
  - npm test
  - npm run coverage
  - npm run codecov
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh scripts/version.sh minor
    on:
     branch: master
  - provider: script
    skip_cleanup: true
    script:  /bin/sh scripts/version.sh patch
    on:
      branch: /$hotfix/
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_KEY
    on:
      branch: release
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      branch:
        - release
        - /$hotfix/