language: node_js
node_js: 6
script:
- npm test
- npm run coverage
- npm run codecov
before_deploy:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git config credential.helper "store --file=.git/credentials"
  - echo "https://${GITHUB_API_KEY}:@github.com" > .git/credentials
  - npm version $VERSION_INCREMENT
after_deploy:
  - git push --tags
deploy:
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_KEY
    on:
      branch: master
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      branch: master