language: node_js
node_js: 6
script:
  - npm test
  - npm run coverage
  - npm run codecov
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh scripts/version.sh
    on:
     condition: $TRAVIS_TAG = ''
