language: node_js
node_js: 6
script:
  - npm test
  - npm run coverage
  - npm run codecov
before_install:
  - git checkout -
deploy:
  - provider: script
    skip_cleanup: true
    script: ./scripts/release.sh
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_KEY
    on:
      condition: -e tmp/flags/gh-pages
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      condition: -e tmp/flags/npm