language: node_js
node_js: 6
script:
  - npm test
  - npm run coverage
  - npm run codecov
before_install:
  - git checkout -
deploy:
  - provider: script
    skip_cleanup: true
    script: /bin/sh scripts/version.sh major
    on:
     branch: major
  - provider: script
    skip_cleanup: true
    script: /bin/sh scripts/version.sh minor
    on:
     branch: release
  - provider: script
    skip_cleanup: true
    script: /bin/sh scripts/version.sh patch
    on:
      branch: hotfix*
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_API_KEY
    on:
      branch: release
  - provider: npm
    skip_cleanup: true
    email: $NPM_EMAIL
    api_key: $NPM_API_KEY
    on:
      branch:
        - release
        - hotfix*